import 'package:eight_course/2_lesson_user_page/user_model.dart';

const String constText =
    'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.';

final List<User> users = [
  User(
    atyJonu: 'Aydar',
    kesibi: 'Flutter developer',
    jash: 20,
    profileSurot: 'FlutterLogo(size: 40)',
    tajryybaJolu: constText,
  ),
  User(
    atyJonu: 'Adilbek',
    kesibi: 'Flutter developer',
    jash: 23,
    profileSurot: 'FlutterLogo(size: 40)',
    tajryybaJolu: constText,
  ),
  User(
    atyJonu: 'Aydar',
    kesibi: 'Flutter developer',
    jash: 20,
    profileSurot: 'FlutterLogo(size: 40)',
    tajryybaJolu: constText,
  ),
  User(
    atyJonu: 'Adilbek',
    kesibi: 'Flutter developer',
    jash: 23,
    profileSurot: 'FlutterLogo(size: 40)',
    tajryybaJolu: constText,
  ),
  User(
    atyJonu: 'Aidar',
    kesibi: 'Flutter developer',
    jash: 20,
    profileSurot: 'FlutterLogo(size: 40)',
    tajryybaJolu: constText,
  ),
  User(
    atyJonu: 'Adilbek',
    kesibi: 'Flutter developer',
    jash: 23,
    profileSurot: 'FlutterLogo(size: 40)',
    tajryybaJolu: constText,
  ),
  User(
    atyJonu: 'Aydar',
    kesibi: 'Flutter developer',
    jash: 20,
    profileSurot: 'FlutterLogo(size: 40)',
    tajryybaJolu: constText,
  ),
  User(
    atyJonu: 'Adilbek',
    kesibi: 'Flutter developer',
    jash: 23,
    profileSurot: 'FlutterLogo(size: 40)',
    tajryybaJolu: constText,
  ),
  User(
    atyJonu: 'Aydar',
    kesibi: 'Flutter developer',
    jash: 20,
    profileSurot: 'FlutterLogo(size: 40)',
    tajryybaJolu: constText,
  ),
  User(
    atyJonu: 'Adilbek',
    kesibi: 'Flutter developer',
    jash: 23,
    profileSurot: 'FlutterLogo(size: 40)',
    tajryybaJolu: constText,
  ),
  User(
    atyJonu: 'Meerim',
    kesibi: 'Flutter developer',
    jash: 19,
    profileSurot: 'FlutterLogo(size: 40)',
    tajryybaJolu: constText,
  ),
  User(
    atyJonu: 'Albina',
    kesibi: 'Flutter developer',
    jash: 23,
    profileSurot: 'FlutterLogo(size: 40)',
    tajryybaJolu: constText,
  ),
  User(
    atyJonu: 'Mayrambek',
    kesibi: 'Flutter developer',
    jash: 43,
    profileSurot: 'FlutterLogo(size: 40)',
    tajryybaJolu: constText,
  ),
  User(
    atyJonu: 'Altynbek',
    kesibi: 'Flutter developer',
    jash: 32,
    profileSurot: 'FlutterLogo(size: 40)',
    tajryybaJolu: constText,
  ),
  User(
    atyJonu: 'Jamal',
    kesibi: 'Flutter developer',
    jash: 27,
    profileSurot: 'FlutterLogo(size: 40)',
    tajryybaJolu: constText,
  ),
  User(
    atyJonu: 'Ivan',
    kesibi: 'Flutter developer',
    jash: 33,
    profileSurot: 'FlutterLogo(size: 40)',
    tajryybaJolu: constText,
  ),
  User(
    atyJonu: 'Oleg',
    kesibi: 'Flutter developer',
    jash: 29,
    profileSurot: 'FlutterLogo(size: 40)',
    tajryybaJolu: constText,
  ),
];
